# Generated by Django 3.2.7 on 2021-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('angle', models.IntegerField()),
                ('switches', models.CharField(max_length=100)),
                ('keycaps', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
            ],
        ),
    ]
