# Generated by Django 3.2.7 on 2021-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
