# Generated by Django 3.2.7 on 2021-09-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyboards', '0002_auto_20210917_1108'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keyboards.keyboards'),
            preserve_default=False,
        ),
    ]
