# Generated by Django 3.2.7 on 2021-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboards',
            name='user',
        ),
        migrations.AddField(
            model_name='keyboards',
            name='keycap_color',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
